### ISSUE TITLE
Audio link not being played

### ISSUE THREAD

**Issue by AbdulAj** [harshalrj25/audioStreamDemo#1]
Hello bro, I have downloaded your project.. really awesome piece of work
I have few song links i have added in playlist, but one of them is playing, rest of three songs not playing
even songs play in browser etc, 
can you please help me in figure out the root cause 
I have also sent you email on mail id. please

**Comment by harshalrj25** [comment]
The URL's you shared in the code are not accessible directly. 
I tried playing them through a web browser.

<img width="1437" alt="Screenshot 2019-06-14 at 2 56 15 PM" src="https://user-images.githubusercontent.com/19181357/59499238-9cf3ed80-8eb4-11e9-9e59-f35d6732a9cc.png">

**Comment by AbdulAj** [comment]
Yes I will send you the file..

**Comment by harshalrj25** [comment]
I haven't heard from you for a while. Closing this issue as it appears to be the URL access issue and not the audioplayer.

**Comment by AbdulAj** [comment]
yes sure
